In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import pandas as pd

df = pd.read_csv('/kaggle/input/datasets/gourisharma32/hr-employee-attrition/WA_Fn-UseC_-HR-Employee-Attrition.csv')

In [2]:
print(df.shape)
print(df.columns)
df.head()

(1470, 35)
Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
# Missing values
df.isnull().sum()

# Duplicate rows
df.duplicated().sum()

# Data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [4]:
df.nunique().sort_values()

EmployeeCount                  1
Over18                         1
StandardHours                  1
Attrition                      2
OverTime                       2
PerformanceRating              2
Gender                         2
BusinessTravel                 3
Department                     3
MaritalStatus                  3
RelationshipSatisfaction       4
StockOptionLevel               4
JobSatisfaction                4
EnvironmentSatisfaction        4
JobInvolvement                 4
WorkLifeBalance                4
Education                      5
JobLevel                       5
EducationField                 6
TrainingTimesLastYear          7
JobRole                        9
NumCompaniesWorked            10
PercentSalaryHike             15
YearsSinceLastPromotion       16
YearsWithCurrManager          18
YearsInCurrentRole            19
DistanceFromHome              29
YearsAtCompany                37
TotalWorkingYears             40
Age                           43
HourlyRate                    71
DailyRate                    886
MonthlyIncome               1349
MonthlyRate                 1427
EmployeeNumber              1470
dtype: int64

In [5]:
df.drop(['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours'], axis=1, inplace=True)

df.shape

(1470, 31)

In [6]:
df['Attrition_Flag'] = df['Attrition'].map({'Yes': 1, 'No': 0})

df[['Attrition', 'Attrition_Flag']].head()

  Attrition  Attrition_Flag
0       Yes               1
1        No               0
2       Yes               1
3        No               0
4        No               0

In [7]:
df['Attrition_Flag'].value_counts()

Attrition_Flag
0    1233
1     237
Name: count, dtype: int64

In [8]:
attrition_rate = df['Attrition_Flag'].mean() * 100
print(round(attrition_rate, 2))

16.12

In [9]:
df['MonthlyIncome'].mean()

np.float64(6502.931292517007)

In [10]:
df['YearsAtCompany'].mean()

np.float64(7.0081632653061225)

In [31]:
tenure_attrition = df.groupby('YearsAtCompany')['Attrition_Flag'].mean() * 100
print(tenure_attrition.head(10).round(2)) #years at company

YearsAtCompany
0    36.36
1    34.50
2    21.26
3    15.62
4    17.27
5    10.71
6    11.84
7    12.22
8    11.25
9     9.76
Name: Attrition_Flag, dtype: float64

In [32]:
pd.crosstab(df['OverTime'], df['Attrition'], normalize='index') * 100  #percent of people leaving in each group

Attrition         No        Yes
OverTime
No         89.563567  10.436433
Yes        69.471154  30.528846

In [33]:
corr = df.corr(numeric_only=True)

corr['Attrition_Flag'].sort_values(ascending=False)

Attrition_Flag              1.000000
DistanceFromHome            0.077924
NumCompaniesWorked          0.043494
MonthlyRate                 0.015170
PerformanceRating           0.002889
HourlyRate                 -0.006846
PercentSalaryHike          -0.013478
Education                  -0.031373
YearsSinceLastPromotion    -0.033019
RelationshipSatisfaction   -0.045872
DailyRate                  -0.056652
TrainingTimesLastYear      -0.059478
WorkLifeBalance            -0.063939
EnvironmentSatisfaction    -0.103369
JobSatisfaction            -0.103481
JobInvolvement             -0.130016
YearsAtCompany             -0.134392
StockOptionLevel           -0.137145
YearsWithCurrManager       -0.156199
Age                        -0.159205
MonthlyIncome              -0.159840
YearsInCurrentRole         -0.160545
JobLevel                   -0.169105
TotalWorkingYears          -0.171063
Name: Attrition_Flag, dtype: float64

In [38]:
df['OverTime_Flag'] = df['OverTime'].map({'Yes':1, 'No':0})

In [39]:
df.drop('MonthlyRate', axis=1, inplace=True)

In [40]:
# Age groups
df['AgeGroup'] = pd.cut(df['Age'], bins=[18,25,35,45,60],
                        labels=['18-25','26-35','36-45','46-60'])

# Income groups
df['IncomeGroup'] = pd.qcut(df['MonthlyIncome'], 4,
                           labels=['Low','Medium','High','Very High'])

In [41]:
df.to_csv('/kaggle/working/hr_clean.csv', index=False)

In [13]:
dept_attrition = df.groupby('Department')['Attrition_Flag'].mean().sort_values(ascending=False) * 100
dept_attrition = dept_attrition.round(2)

print(dept_attrition)

Department
Sales                     20.63
Human Resources           19.05
Research & Development    13.84
Name: Attrition_Flag, dtype: float64

In [14]:
pd.crosstab(df['Department'], df['Attrition'])

Attrition                No  Yes
Department
Human Resources          51   12
Research & Development  828  133
Sales                   354   92

In [15]:
pd.crosstab([df['Department'], df['JobLevel']], df['Attrition_Flag'], normalize='index') * 100

Attrition_Flag                            0          1
Department             JobLevel
Human Resources        1          69.696970  30.303030
                       2         100.000000   0.000000
                       3          66.666667  33.333333
                       4         100.000000   0.000000
                       5         100.000000   0.000000
Research & Development 1          76.728111  23.271889
                       2          94.661922   5.338078
                       3          89.922481  10.077519
                       4          98.529412   1.470588
                       5          93.877551   6.122449
Sales                  1          57.894737  42.105263
                       2          84.583333  15.416667
                       3          79.518072  20.481928
                       4          88.235294  11.764706
                       5          84.615385  15.384615

In [17]:
ot_attrition = df.groupby('OverTime')['Attrition_Flag'].mean() * 100
print(ot_attrition.round(2))

OverTime
No     10.44
Yes    30.53
Name: Attrition_Flag, dtype: float64

In [18]:
pd.crosstab(df['OverTime'], df['Attrition'], normalize='index') * 100

Attrition         No        Yes
OverTime
No         89.563567  10.436433
Yes        69.471154  30.528846

In [19]:
pd.crosstab(df['Department'], df['OverTime'], df['Attrition_Flag'], aggfunc='mean') * 100

OverTime                       No        Yes
Department
Human Resources         15.217391  29.411765
Research & Development   8.550725  27.306273
Sales                   13.836478  37.500000

In [21]:
js_attrition = df.groupby('JobSatisfaction')['Attrition_Flag'].mean() * 100
print(js_attrition.round(2))

JobSatisfaction
1    22.84
2    16.43
3    16.52
4    11.33
Name: Attrition_Flag, dtype: float64

In [22]:
pd.crosstab(df['JobSatisfaction'], df['Attrition'], normalize='index') * 100

Attrition               No        Yes
JobSatisfaction
1                77.162630  22.837370
2                83.571429  16.428571
3                83.484163  16.515837
4                88.671024  11.328976

In [23]:
pd.crosstab([df['OverTime'], df['JobSatisfaction']], df['Attrition_Flag'], normalize='index') * 100

Attrition_Flag                    0          1
OverTime JobSatisfaction
No       1                82.439024  17.560976
         2                90.521327   9.478673
         3                90.031153   9.968847
         4                93.059937   6.940063
Yes      1                64.285714  35.714286
         2                62.318841  37.681159
         3                66.115702  33.884298
         4                78.873239  21.126761

In [25]:
jl_attrition = df.groupby('JobLevel')['Attrition_Flag'].mean() * 100
print(jl_attrition.round(2))

JobLevel
1    26.34
2     9.74
3    14.68
4     4.72
5     7.25
Name: Attrition_Flag, dtype: float64

In [26]:
pd.crosstab([df['JobLevel'], df['OverTime']], df['Attrition_Flag'], normalize='index') * 100  #job level and overtime

Attrition_Flag             0          1
JobLevel OverTime
1        No        84.237726  15.762274
         Yes       47.435897  52.564103
2        No        93.298969   6.701031
         Yes       82.191781  17.808219
3        No        87.741935  12.258065
         Yes       79.365079  20.634921
4        No        97.260274   2.739726
         Yes       90.909091   9.090909
5        No        96.078431   3.921569
         Yes       83.333333  16.666667

In [27]:
df.groupby('Attrition')['MonthlyIncome'].mean()

Attrition
No     6832.739659
Yes    4787.092827
Name: MonthlyIncome, dtype: float64